"""creator os: brands, pipeline runs, opportunities, learnings

Revision ID: 7e48a7c0ef51
Revises: 182a492d4e63
Create Date: 2026-07-10 17:32:34.660456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e48a7c0ef51'
down_revision: Union[str, None] = '182a492d4e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('voice', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('guidelines', sa.Text(), nullable=False),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('goals', sa.Text(), nullable=False),
    sa.Column('memory', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learnings_brand_id'), 'learnings', ['brand_id'], unique=False)
    op.create_index(op.f('ix_learnings_kind'), 'learnings', ['kind'], unique=False)
    op.create_index(op.f('ix_learnings_project_id'), 'learnings', ['project_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_brand_id'), 'opportunities', ['brand_id'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_stage', sa.String(length=30), nullable=False),
    sa.Column('log', sa.JSON(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_project_id'), 'pipeline_runs', ['project_id'], unique=False)
    op.add_column('comfy_jobs', sa.Column('workflow_def_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_comfy_jobs_workflow_def_id'), 'comfy_jobs', ['workflow_def_id'], unique=False)
    op.add_column('projects', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_brand_id'), 'projects', ['brand_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_brand_id'), table_name='projects')
    op.drop_column('projects', 'brand_id')
    op.drop_index(op.f('ix_comfy_jobs_workflow_def_id'), table_name='comfy_jobs')
    op.drop_column('comfy_jobs', 'workflow_def_id')
    op.drop_index(op.f('ix_pipeline_runs_project_id'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_opportunities_brand_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_learnings_project_id'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_kind'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_brand_id'), table_name='learnings')
    op.drop_table('learnings')
    op.drop_table('brands')
    # ### end Alembic commands ###
