"""brand engine preferences

Revision ID: 9b6ae3ffca66
Revises: 7e48a7c0ef51
Create Date: 2026-07-10 17:55:39.427019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9b6ae3ffca66'
down_revision: Union[str, None] = '7e48a7c0ef51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('preferred_provider', sa.String(length=50), nullable=False))
    op.add_column('brands', sa.Column('preferred_model', sa.String(length=100), nullable=False))
    op.add_column('brands', sa.Column('preferred_workflow_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brands', 'preferred_workflow_id')
    op.drop_column('brands', 'preferred_model')
    op.drop_column('brands', 'preferred_provider')
    # ### end Alembic commands ###
