"""workflow management flags

Revision ID: ff13f0dcce8f
Revises: 9b6ae3ffca66
Create Date: 2026-07-11 04:37:22.266404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision: str = 'ff13f0dcce8f'
down_revision: Union[str, None] = '9b6ae3ffca66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_jobs_project_id'), table_name='voice_jobs')
    op.drop_table('voice_jobs')
    # server defaults required: SQLite cannot ADD NOT NULL columns to populated tables
    op.add_column('workflow_defs', sa.Column('source', sa.String(length=20), nullable=False, server_default='manual'))
    op.add_column('workflow_defs', sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('workflow_defs', sa.Column('favorite', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workflow_defs', sa.Column('wf_type', sa.String(length=30), nullable=False, server_default='other'))
    op.add_column('workflow_defs', sa.Column('models', sa.JSON(), nullable=False, server_default='[]'))
    op.add_column('workflow_defs', sa.Column('vram_estimate_mb', sa.Integer(), nullable=True))
    op.add_column('workflow_defs', sa.Column('content_types', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_defs', 'content_types')
    op.drop_column('workflow_defs', 'vram_estimate_mb')
    op.drop_column('workflow_defs', 'models')
    op.drop_column('workflow_defs', 'wf_type')
    op.drop_column('workflow_defs', 'favorite')
    op.drop_column('workflow_defs', 'enabled')
    op.drop_column('workflow_defs', 'source')
    op.create_table('voice_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('engine', sa.VARCHAR(length=30), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('voice', sa.VARCHAR(length=200), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('output_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_jobs_project_id'), 'voice_jobs', ['project_id'], unique=False)
    # ### end Alembic commands ###
